title: Pytest Experiment # Learning Lab course
tagline: Trying out CI with learning lab # Description for your course, displayed on the course catalog
description: Description # Longer description for course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is created for each individual learner

template:
  name: pytest-ci-course # the name of the repository when it is created for the learner
  repo: pytest-ci-template # the name of the repository to be copied, must have the same owner as the course. If omitted, the learner's repository will be empty.
  description: Description # (OPTIONAL) A one-line description which will be set for the GitHub repository.

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo
# You can execute multiple actions in the `before` block. Refer to https://lab.github.com/docs/before-block
# Some actions require additional options as the one shown below, those options should appear below `type:`
# Below are example actions, full list at https://lab.github.com/docs/actions/
before:
- type: updateBranchProtection # Protects the master branch 
- type: createIssue
  title: There's a bug!
  body: 01_NanoMFG.md
  store:
    first_issue_url: "{{ result.data.html_url }}"

steps:
# Step 1: Create pull request
  - title: Use a templated workflow
    description: Create a pull request with a templated workflow
    event: pull_request
    link: "{{ store.first_issue_url }}"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: CI for Python
        else:
          - type: respond
            with: e-failed-run.md
        store:
          ci_for_node_pr: "{{ payload.pull_request.number }}"
      - type: createPullRequest
        title: Add Pytests
        body: 0X_merge.md
        base: "%payload.pull_request.head.ref%"
        head: fix-pytest
        store:
          second_pr_url: "{{ result.data.html_url }}"
# Step 2: Fix Pytest 
  - title: Fix the test
    description: Edit the file that's causing the test to fail
    event: check_suite.completed
    link: "{{ store.first_pr_url }}"
    actions:
      - type: gate
        left: "%payload.check_suite.app.slug%"
        operator: ===
        right: github-actions
      - type: gate
        left: "%payload.check_suite.conclusion%"
        operator: ===
        right: success
        else:
          - type: respond
            with: e-failed-run.md
      - type: createReview
        event: APPROVE
        body: 0X_merge.md
        pullRequest: CI for Node

